# Habibi-Go Configuration Example

server:
  host: "localhost"  # Use "0.0.0.0" to listen on all interfaces
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  shutdown_timeout: "10s"
  
  # Basic authentication (optional)
  auth:
    enabled: false  # Set to true to enable authentication
    username: ""   # Your username
    password: ""   # Your password

database:
  path: "~/.habibi-go/habibi.db"
  backup_enabled: true
  backup_interval: "24h"
  max_connections: 10

projects:
  default_directory: "~/projects"
  auto_discover: false
  worktree_base_path: ".worktrees"

agents:
  default_timeout: "30m"
  max_concurrent: 10
  health_check_interval: "30s"
  log_retention_days: 7
  resource_limits:
    memory_mb: 1024
    cpu_percent: 50
  # Path to Claude binary - defaults to 'claude' (looks in PATH)
  # Uncomment and set if Claude is installed in a non-standard location
  # claude_binary_path: "/usr/local/bin/claude"

slack:
  enabled: false
  notification_channel: "#dev"

logging:
  level: "info"
  format: "json"
  file_path: "~/.habibi-go/logs/app.log"
  max_size_mb: 100
  max_backups: 5